sudo: required

language: node_js
node_js: 
  - "node"

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yurykovshov/my-web-front .
  - docker push yurykovshov/my-web-front